version: 2

project_name: wordenc

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: wordenc
    main: ./cmd/wordenc
    binary: wordenc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    builds: [wordenc]
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
